version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: appdatabase
    ports:
      - "27017:27017"
  task-tracker:
    image: task-tracker
    depends_on:
      - mongodb
    environment:
      - "MONGODB_HOST=mongodb"
    ports:
      - "8081:8081"