spring:
  application:
    name: newsService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SERVER_URL:jdbc:postgresql://localhost:5432/news_service_db}
    username: ${SERVER_USERNAME:postgres}
    password: ${SERVER_PASS:1322}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

app:
  jwt:
    secretKey: "===============secret=====Key=====Some==============="
    tokenExpiration: 5m
    refreshTokenExpiration: 30m
  redis:
    enabled: ${REDIS_ENABLED:false}

server:
  port: 8081