spring:
  data:
    mongodb:
      username: root
      password: root
      host: ${MONGODB_HOST:localhost}
      database: appdatabase
      authentication-database: admin
      auto-index-creation: true

app:
  jwt:
    secretKey: "===============secret=====Key=====Some==============="
    tokenExpiration: 10m

server:
  port: 8081